Better distinguish with Parse-Swift
netreconlab/Parse-Swift pull request #22
Opened 2022-11-24 15:53 UTC by Kondamon

I have tried to summarise all your arguments in a brief manner and added it to the top on the readme, so it's easier visible for new users who could be confused at the beginning (as I was). Furthermore I would recommend to use the name Parse-Swift++ to be able to easier distinguish this repo from the community edition.

2022-11-24 16:54 UTC, cbaker6 requested changes
Thanks for opening this PR, I really appreciate it! I made some minor updates. I really like your idea of naming this repo something different to distinguish from the other. I'm leaning towards Parse-Swift<sup>OG</sup> since it's developed and maintained by one of its' `original` developers and will maintain the path of it's `original` direction. Are you able to update your logo change to show Parse-Swift<sup>OG</sup>

2022-11-24 16:54 UTC, cbaker6 commented on README.md
> +> Parse-Swift++ has the most up-to-date features and bug fixes for Parse-Swift. It is the most flexible Parse Client SDK to date, the only SDK with zero dependencies, works with Cloud Code, all of wh
```suggestion
> Parse-Swift<sup>OG</sup> has the most up-to-date features and bug fixes to develop client and server-side applications. It is the most flexible Parse Client SDK to date, can be used to write [Cloud Code](https://github.com/netreconlab/parse-server-swift), and is developed with zero dependencies. This repo is aligned with the original core principals of a swifty framework. Star, watch, and submit issues and pull requests to https://github.com/netreconlab/Parse-Swift instead of the Parse-Community Parse-Swift to support it's development. <a href="#why-parse-swift">Get more info</a>.
```

2022-11-24 17:14 UTC, Kondamon commented
You are welcome, I have updated the logo!

2022-11-24 22:51 UTC, cbaker6 commented
For some reason, the logo didn’t update in the readme https://github.com/Kondamon/Parse-Swift/blob/main/README.md

2022-11-25 08:26 UTC, Kondamon commented
I have set a relative path for the suborder, now it works!

2022-11-25 16:15 UTC, cbaker6 approved these changes
LGTM!

2022-11-25 16:16 UTC, merged